"""create order table

Revision ID: 4f09171eb0da
Revises:
Create Date: 2025-03-08 13:47:45.879701

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4f09171eb0da"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("user_uuid", sa.UUID(), nullable=False, comment="Айди пользователя"),
        sa.Column(
            "status",
            postgresql.ENUM(
                "CREATED",
                "PROCESSING",
                "READY",
                "CANCELED",
                name="order_status",
            ),
            nullable=False,
            comment="Статус заказа",
        ),
        sa.Column("address", sa.Text(), nullable=False, comment="Адрес доставки"),
        sa.Column("price", sa.DECIMAL(), nullable=False, comment="Стоимость заказа"),
        sa.Column(
            "is_payed",
            sa.Boolean(),
            nullable=False,
            comment="Оплачен ли заказ",
        ),
        sa.Column(
            "pay_method",
            postgresql.ENUM("CASH", "CARD", name="pay_method"),
            nullable=False,
            comment="Способ оплаты",
        ),
        sa.Column(
            "comment",
            sa.String(),
            nullable=False,
            comment="Комментарий к заказу",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_orders_user_uuid"), "orders", ["user_uuid"], unique=True)
    op.create_index(op.f("ix_orders_uuid"), "orders", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_uuid"), table_name="orders")
    op.drop_index(op.f("ix_orders_user_uuid"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
