"""created order_item table

Revision ID: 285f1baa702c
Revises: 4f09171eb0da
Create Date: 2025-03-09 15:09:37.010641

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "285f1baa702c"
down_revision: Union[str, None] = "4f09171eb0da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column(
            "quantity",
            sa.Integer(),
            nullable=False,
            comment="Количество элементов",
        ),
        sa.Column("order_id", sa.UUID(), nullable=True, comment="Айди заказа"),
        sa.Column("item_uuid", sa.UUID(), nullable=False, comment="Айди товара"),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_order_items_item_uuid"),
        "order_items",
        ["item_uuid"],
        unique=True,
    )
    op.create_index(op.f("ix_order_items_uuid"), "order_items", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_items_uuid"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_item_uuid"), table_name="order_items")
    op.drop_table("order_items")
    # ### end Alembic commands ###
